from fastapi import APIRouter, HTTPException, Depends
from app.schemas.schemas import TripCreate, TripOut, TravelMode
from app.services.ai_planner import generate_itinerary
from app.core.auth import get_current_user

router = APIRouter()

# In-memory trip store (replace with DB later)
_trips: dict = {}


@router.post("/generate", response_model=TripOut, status_code=201)
async def create_trip(data: TripCreate, current_user: dict = Depends(get_current_user)):
    """
    Generate an AI-powered road trip itinerary.

    OWN VEHICLE mode:
      - Provide origin, destination, vehicle_id, dates, budget
      - Returns full route with fuel stops, toll, food,
        destination itinerary and return route

    PUBLIC TRANSPORT mode (bus/train/flight):
      - Provide destination, dates, budget
      - vehicle_id is NOT needed
      - Returns destination itinerary only
        (places, hotels, food)
    """

    # ── Validate own vehicle request ──────────────────────────────────────
    if data.travel_mode == TravelMode.own_vehicle:
        if not data.vehicle_id:
            raise HTTPException(
                status_code=400,
                detail="vehicle_id is required for own vehicle mode"
            )
        if not data.origin:
            raise HTTPException(
                status_code=400,
                detail="origin is required for own vehicle mode"
            )
        # In production: fetch real vehicle from DB using data.vehicle_id
        vehicle_info = {
            "fuel_type": "petrol",
            "category": "car",
            "mileage_kmpl": 15.0,
        }
    else:
        # Public transport — no vehicle needed
        vehicle_info = {}

    try:
        trip = await generate_itinerary(data, vehicle_info)
        trip_dict = trip.model_dump()
        trip_dict["user_id"] = current_user["user_id"]
        _trips[trip.id] = trip_dict
        return trip
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/my", response_model=list[TripOut])
def list_my_trips(current_user: dict = Depends(get_current_user)):
    """
    List all trips generated by the logged-in user.
    Shows both own vehicle and public transport trips.
    """
    user_id = current_user["user_id"]
    return [
        TripOut(**t)
        for t in _trips.values()
        if t.get("user_id") == user_id
    ]


@router.get("/{trip_id}", response_model=TripOut)
def get_trip(trip_id: str, current_user: dict = Depends(get_current_user)):
    """
    Get a single trip by ID.
    Shows full itinerary with cost breakdown.
    """
    trip = _trips.get(trip_id)
    if not trip:
        raise HTTPException(status_code=404, detail="Trip not found")
    if trip.get("user_id") != current_user["user_id"]:
        raise HTTPException(status_code=403, detail="Not your trip")
    return TripOut(**trip)


@router.get("/{trip_id}/cost", )
def get_trip_cost(trip_id: str, current_user: dict = Depends(get_current_user)):
    """
    Get the full cost breakdown for a trip.

    Own Vehicle:
      fuel cost + toll cost + hotel cost + food cost = grand total

    Public Transport:
      transport fare + return fare + hotel cost + food cost = grand total
    """
    trip = _trips.get(trip_id)
    if not trip:
        raise HTTPException(status_code=404, detail="Trip not found")
    if trip.get("user_id") != current_user["user_id"]:
        raise HTTPException(status_code=403, detail="Not your trip")

    mode = trip.get("travel_mode")

    if mode == TravelMode.own_vehicle:
        fuel  = trip.get("fuel_cost_inr", 0)
        toll  = trip.get("toll_cost_inr", 0)
        hotel = trip.get("hotel_cost_inr", 0)
        food  = trip.get("food_cost_inr", 0)
        total = fuel + toll + hotel + food
        return {
            "trip_id": trip_id,
            "travel_mode": mode,
            "breakdown": {
                "fuel_cost_inr":      fuel,
                "toll_cost_inr":      toll,
                "hotel_cost_inr":     hotel,
                "food_cost_inr":      food,
            },
            "grand_total_inr": total,
        }
    else:
        going   = trip.get("transport_fare_inr", 0)
        returns = trip.get("return_fare_inr", 0)
        hotel   = trip.get("hotel_cost_inr", 0)
        food    = trip.get("food_cost_inr", 0)
        total   = going + returns + hotel + food
        return {
            "trip_id": trip_id,
            "travel_mode": mode,
            "breakdown": {
                "going_fare_inr":     going,
                "return_fare_inr":    returns,
                "hotel_cost_inr":     hotel,
                "food_cost_inr":      food,
            },
            "grand_total_inr": total,
        }


@router.delete("/{trip_id}", status_code=204)
def delete_trip(trip_id: str, current_user: dict = Depends(get_current_user)):
    """Delete a trip."""
    trip = _trips.get(trip_id)
    if not trip:
        raise HTTPException(status_code=404, detail="Trip not found")
    if trip.get("user_id") != current_user["user_id"]:
        raise HTTPException(status_code=403, detail="Not your trip")
    del _trips[trip_id]
