from fastapi import APIRouter, HTTPException, Depends
from app.schemas.schemas import TripCreate, TripOut
from app.services.ai_planner import generate_itinerary
from app.core.auth import get_current_user

router = APIRouter()

# In-memory trip store (replace with DB later)
_trips: dict = {}
_vehicles: dict = {}   # shared reference — in real app, call DB


@router.post("/generate", response_model=TripOut, status_code=201)
async def create_trip(data: TripCreate, current_user: dict = Depends(get_current_user)):
    """
    Generate an AI-powered road trip itinerary.

    Provide your vehicle_id (from /api/users/vehicles),
    origin, destination, dates, budget, and group type.
    The AI will return a full day-by-day itinerary.
    """
    # In production: fetch vehicle from DB using data.vehicle_id
    # For now we pass a default vehicle so the mock works without a DB
    vehicle_info = {
        "fuel_type": "petrol",
        "category": "car",
        "mileage_kmpl": 15.0,
    }

    try:
        trip = await generate_itinerary(data, vehicle_info)
        trip_dict = trip.model_dump()
        trip_dict["user_id"] = current_user["user_id"]
        _trips[trip.id] = trip_dict
        return trip
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{trip_id}", response_model=TripOut)
def get_trip(trip_id: str, current_user: dict = Depends(get_current_user)):
    """Fetch a previously generated trip by ID."""
    trip = _trips.get(trip_id)
    if not trip:
        raise HTTPException(status_code=404, detail="Trip not found")
    return TripOut(**trip)


@router.get("/", response_model=list[TripOut])
def list_my_trips(current_user: dict = Depends(get_current_user)):
    """List all trips generated by the logged-in user."""
    user_id = current_user["user_id"]
    return [TripOut(**t) for t in _trips.values() if t.get("user_id") == user_id]


@router.delete("/{trip_id}", status_code=204)
def delete_trip(trip_id: str, current_user: dict = Depends(get_current_user)):
    """Delete a trip."""
    trip = _trips.get(trip_id)
    if not trip:
        raise HTTPException(status_code=404, detail="Trip not found")
    if trip.get("user_id") != current_user["user_id"]:
        raise HTTPException(status_code=403, detail="Not your trip")
    del _trips[trip_id]
