"""add hotel train bus flight providers

Revision ID: f6fe9b2ec4c0
Revises: 005cb4079064
Create Date: 2026-06-17 11:02:12.056913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6fe9b2ec4c0'
down_revision: Union[str, Sequence[str], None] = '005cb4079064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('bus_type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=False),
    sa.Column('duration_hrs', sa.Float(), nullable=False),
    sa.Column('fare_inr', sa.Float(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('seats_booked', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buses_destination'), 'buses', ['destination'], unique=False)
    op.create_index(op.f('ix_buses_id'), 'buses', ['id'], unique=False)
    op.create_index(op.f('ix_buses_origin'), 'buses', ['origin'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('airline', sa.String(), nullable=False),
    sa.Column('flight_number', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=False),
    sa.Column('duration_hrs', sa.Float(), nullable=False),
    sa.Column('fare_inr', sa.Float(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('seats_booked', sa.Integer(), nullable=True),
    sa.Column('travel_class', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_destination'), 'flights', ['destination'], unique=False)
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_index(op.f('ix_flights_origin'), 'flights', ['origin'], unique=False)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('star_rating', sa.Float(), nullable=True),
    sa.Column('price_per_night_inr', sa.Float(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=True),
    sa.Column('rooms_booked', sa.Integer(), nullable=True),
    sa.Column('amenities', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_email'), 'providers', ['email'], unique=True)
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_name', sa.String(), nullable=False),
    sa.Column('train_number', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=False),
    sa.Column('duration_hrs', sa.Float(), nullable=False),
    sa.Column('fare_inr', sa.Float(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('seats_booked', sa.Integer(), nullable=True),
    sa.Column('travel_class', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_destination'), 'trains', ['destination'], unique=False)
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_origin'), 'trains', ['origin'], unique=False)
    op.create_table('bus_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(), nullable=False),
    sa.Column('travel_date', sa.String(), nullable=False),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('total_fare_inr', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_bookings_id'), 'bus_bookings', ['id'], unique=False)
    op.create_table('flight_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(), nullable=False),
    sa.Column('travel_date', sa.String(), nullable=False),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('total_fare_inr', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_bookings_id'), 'flight_bookings', ['id'], unique=False)
    op.create_table('hotel_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.String(), nullable=False),
    sa.Column('check_out_date', sa.String(), nullable=False),
    sa.Column('num_rooms', sa.Integer(), nullable=True),
    sa.Column('num_guests', sa.Integer(), nullable=True),
    sa.Column('total_price_inr', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_bookings_id'), 'hotel_bookings', ['id'], unique=False)
    op.create_table('train_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(), nullable=False),
    sa.Column('travel_date', sa.String(), nullable=False),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('total_fare_inr', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_bookings_id'), 'train_bookings', ['id'], unique=False)
    op.create_table('provider_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(), nullable=False),
    sa.Column('travel_date', sa.String(), nullable=False),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('pickup_location', sa.String(), nullable=True),
    sa.Column('total_fare_inr', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['provider_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_bookings_id'), 'provider_bookings', ['id'], unique=False)

    # ── Drop old tables in correct order (children before parents) ──────────

    # 1. Deepest children first: bus_ticket_bookings & vehicle_rental_bookings
    op.drop_index(op.f('ix_bus_ticket_bookings_id'), table_name='bus_ticket_bookings')
    op.drop_table('bus_ticket_bookings')

    op.drop_index(op.f('ix_vehicle_rental_bookings_id'), table_name='vehicle_rental_bookings')
    op.drop_table('vehicle_rental_bookings')

    # 2. bus_seat_availability depends on provider_bus_services
    op.drop_index(op.f('ix_bus_seat_availability_id'), table_name='bus_seat_availability')
    op.drop_index(op.f('ix_bus_seat_availability_travel_date'), table_name='bus_seat_availability')
    op.drop_table('bus_seat_availability')

    # 3. provider_bus_services depends on service_providers
    op.drop_index(op.f('ix_provider_bus_services_destination_city'), table_name='provider_bus_services')
    op.drop_index(op.f('ix_provider_bus_services_id'), table_name='provider_bus_services')
    op.drop_index(op.f('ix_provider_bus_services_origin_city'), table_name='provider_bus_services')
    op.drop_table('provider_bus_services')

    # 4. Drop FK from provider_vehicles -> service_providers so we can drop service_providers
    op.drop_constraint('provider_vehicles_provider_id_fkey', 'provider_vehicles', type_='foreignkey')

    # 5. Now safe to drop service_providers
    op.drop_index(op.f('ix_service_providers_email'), table_name='service_providers')
    op.drop_index(op.f('ix_service_providers_id'), table_name='service_providers')
    op.drop_table('service_providers')

    # ── Alter provider_vehicles ──────────────────────────────────────────────

    # Add nullable=True first, backfill, then enforce NOT NULL
    op.add_column('provider_vehicles', sa.Column('vehicle_name', sa.String(), nullable=True))
    op.execute("UPDATE provider_vehicles SET vehicle_name = 'Unknown' WHERE vehicle_name IS NULL")
    op.alter_column('provider_vehicles', 'vehicle_name', nullable=False)

    op.add_column('provider_vehicles', sa.Column('driver_included', sa.Boolean(), nullable=True))

    op.add_column('provider_vehicles', sa.Column('origin', sa.String(), nullable=True))
    op.execute("UPDATE provider_vehicles SET origin = 'Unknown' WHERE origin IS NULL")
    op.alter_column('provider_vehicles', 'origin', nullable=False)

    op.add_column('provider_vehicles', sa.Column('destination', sa.String(), nullable=True))
    op.execute("UPDATE provider_vehicles SET destination = 'Unknown' WHERE destination IS NULL")
    op.alter_column('provider_vehicles', 'destination', nullable=False)

    op.add_column('provider_vehicles', sa.Column('departure_time', sa.String(), nullable=True))
    op.add_column('provider_vehicles', sa.Column('price_per_km_inr', sa.Float(), nullable=True))
    op.add_column('provider_vehicles', sa.Column('fixed_fare_inr', sa.Float(), nullable=True))
    op.add_column('provider_vehicles', sa.Column('total_seats', sa.Integer(), nullable=True))
    op.add_column('provider_vehicles', sa.Column('seats_booked', sa.Integer(), nullable=True))
    op.add_column('provider_vehicles', sa.Column('is_active', sa.Boolean(), nullable=True))

    op.drop_index(op.f('ix_provider_vehicles_base_city'), table_name='provider_vehicles')
    op.drop_index(op.f('ix_provider_vehicles_registration_number'), table_name='provider_vehicles')
    op.create_index(op.f('ix_provider_vehicles_destination'), 'provider_vehicles', ['destination'], unique=False)
    op.create_index(op.f('ix_provider_vehicles_origin'), 'provider_vehicles', ['origin'], unique=False)

    # FK was already dropped above; recreate pointing to new `providers` table
    # Clear orphaned provider_vehicles rows that reference old service_providers data
    op.execute('DELETE FROM provider_vehicles WHERE provider_id NOT IN (SELECT id FROM providers)')
    # Recreate FK pointing to new `providers` table
    op.create_foreign_key(None, 'provider_vehicles', 'providers', ['provider_id'], ['id'])

    op.drop_column('provider_vehicles', 'is_available')
    op.drop_column('provider_vehicles', 'seating_capacity')
    op.drop_column('provider_vehicles', 'fuel_type')
    op.drop_column('provider_vehicles', 'base_city')
    op.drop_column('provider_vehicles', 'price_per_km')
    op.drop_column('provider_vehicles', 'ac_available')
    op.drop_column('provider_vehicles', 'registration_number')
    op.drop_column('provider_vehicles', 'brand')
    op.drop_column('provider_vehicles', 'price_per_day')
    op.drop_column('provider_vehicles', 'image_url')
    op.drop_column('provider_vehicles', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_vehicles', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('provider_vehicles', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('provider_vehicles', sa.Column('price_per_day', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('provider_vehicles', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('provider_vehicles', sa.Column('registration_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('provider_vehicles', sa.Column('ac_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('provider_vehicles', sa.Column('price_per_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('provider_vehicles', sa.Column('base_city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('provider_vehicles', sa.Column('fuel_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('provider_vehicles', sa.Column('seating_capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('provider_vehicles', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'provider_vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('provider_vehicles_provider_id_fkey'), 'provider_vehicles', 'service_providers', ['provider_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_provider_vehicles_origin'), table_name='provider_vehicles')
    op.drop_index(op.f('ix_provider_vehicles_destination'), table_name='provider_vehicles')
    op.create_index(op.f('ix_provider_vehicles_registration_number'), 'provider_vehicles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_provider_vehicles_base_city'), 'provider_vehicles', ['base_city'], unique=False)
    op.drop_column('provider_vehicles', 'is_active')
    op.drop_column('provider_vehicles', 'seats_booked')
    op.drop_column('provider_vehicles', 'total_seats')
    op.drop_column('provider_vehicles', 'fixed_fare_inr')
    op.drop_column('provider_vehicles', 'price_per_km_inr')
    op.drop_column('provider_vehicles', 'departure_time')
    op.drop_column('provider_vehicles', 'destination')
    op.drop_column('provider_vehicles', 'origin')
    op.drop_column('provider_vehicles', 'driver_included')
    op.drop_column('provider_vehicles', 'vehicle_name')
    op.create_table('bus_ticket_bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bus_service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('travel_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('num_seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seat_numbers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_fare', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('passenger_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('passenger_phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bus_service_id'], ['provider_bus_services.id'], name=op.f('bus_ticket_bookings_bus_service_id_fkey')),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], name=op.f('bus_ticket_bookings_provider_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bus_ticket_bookings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bus_ticket_bookings_pkey'))
    )
    op.create_index(op.f('ix_bus_ticket_bookings_id'), 'bus_ticket_bookings', ['id'], unique=False)
    op.create_table('vehicle_rental_bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pickup_city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dropoff_city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pickup_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('dropoff_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], name=op.f('vehicle_rental_bookings_provider_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vehicle_rental_bookings_user_id_fkey')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['provider_vehicles.id'], name=op.f('vehicle_rental_bookings_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_rental_bookings_pkey'))
    )
    op.create_index(op.f('ix_vehicle_rental_bookings_id'), 'vehicle_rental_bookings', ['id'], unique=False)
    op.create_table('provider_bus_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bus_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bus_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('origin_city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('destination_city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('via_cities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('departure_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('arrival_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration_hrs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fare_per_seat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('amenities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['service_providers.id'], name=op.f('provider_bus_services_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('provider_bus_services_pkey'))
    )
    op.create_index(op.f('ix_provider_bus_services_origin_city'), 'provider_bus_services', ['origin_city'], unique=False)
    op.create_index(op.f('ix_provider_bus_services_id'), 'provider_bus_services', ['id'], unique=False)
    op.create_index(op.f('ix_provider_bus_services_destination_city'), 'provider_bus_services', ['destination_city'], unique=False)
    op.create_table('bus_seat_availability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bus_service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('travel_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('seats_booked', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seats_available', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bus_service_id'], ['provider_bus_services.id'], name=op.f('bus_seat_availability_bus_service_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bus_seat_availability_pkey'))
    )
    op.create_index(op.f('ix_bus_seat_availability_travel_date'), 'bus_seat_availability', ['travel_date'], unique=False)
    op.create_index(op.f('ix_bus_seat_availability_id'), 'bus_seat_availability', ['id'], unique=False)
    op.create_table('service_providers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('license_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gst_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('service_providers_pkey'))
    )
    op.create_index(op.f('ix_service_providers_id'), 'service_providers', ['id'], unique=False)
    op.create_index(op.f('ix_service_providers_email'), 'service_providers', ['email'], unique=True)
    op.drop_index(op.f('ix_provider_bookings_id'), table_name='provider_bookings')
    op.drop_table('provider_bookings')
    op.drop_index(op.f('ix_train_bookings_id'), table_name='train_bookings')
    op.drop_table('train_bookings')
    op.drop_index(op.f('ix_hotel_bookings_id'), table_name='hotel_bookings')
    op.drop_table('hotel_bookings')
    op.drop_index(op.f('ix_flight_bookings_id'), table_name='flight_bookings')
    op.drop_table('flight_bookings')
    op.drop_index(op.f('ix_bus_bookings_id'), table_name='bus_bookings')
    op.drop_table('bus_bookings')
    op.drop_index(op.f('ix_trains_origin'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_index(op.f('ix_trains_destination'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_email'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_flights_origin'), table_name='flights')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_buses_origin'), table_name='buses')
    op.drop_index(op.f('ix_buses_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_destination'), table_name='buses')
    op.drop_table('buses')
    # ### end Alembic commands ###